name: test_api
on:
  push:
    branches: [midterm] 
jobs:
  test_flow:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello World

  test_api:
    runs-on: ubuntu-lastest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    env:
      MONGODB_DATABASE: flaskdb
      MONGODB_HOSTNAME: localhost
    steps:
      - uses: actions/checkout@v2
      - name: Build mock database
        run: docker build -t db source/db -p 27017:27017
      - name: Run mock database
        run: docker run db
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Pytest
        run: python -m pip install pytest
      - name: Run tests
        run: pytest
            
            