name: Build and Push Images to Dockerhub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract version
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Login Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v4
        with:
          context: ./'10. GK'/DoBaoHoang/source/api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api:${{ steps.vars.outputs.tag }}

      - name: Build and push Web server image
        uses: docker/build-push-action@v4
        with:
          context: ./'10. GK'/DoBaoHoang/source/server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web:${{ steps.vars.outputs.tag }}

      - name: Build and push DB image
        uses: docker/build-push-action@v4
        with:
          context: ./'10. GK'/DoBaoHoang/source/db
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/db:${{ steps.vars.outputs.tag }}