name: test_api
on:
  push:
    branches: [midterm] 
jobs:
  test_flow:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello World

  test_api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    env:
      MONGODB_DATABASE: flaskdb
      MONGODB_HOSTNAME: localhost
    steps:
      - uses: actions/checkout@v2

      - name: Create network
        run: docker network create --driver bridge test_net

      - name: Build mock database
        run: docker build -t db ${{ github.workspace }}/"10. GK"/DoBaoHoang/source/db
      - name: Run mock database
        run: docker run -p 27017:27017 --network test_net --name db -d db 

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install denpendencies
        run: pip install -r ${{ github.workspace }}/"10. GK"/DoBaoHoang/source/api/tests/requirements.txt

      - name: Build api server
        run: docker build -t api  ${{ github.workspace }}/"10. GK"/DoBaoHoang/source/api
      - name: Run api server
        run: |
            docker run -p 8080:8080 --network test_net --name api -d \
            -e MONGODB_DATABASE=${{ github.env.MONGODB_DATABASE }} \
            -e MONGODB_HOSTNAME=${{ github.env.MONGODB_HOSTNAME }} \
            api

      - name: Run tests
        run: pytest ${{ github.workspace }}/"10. GK"/DoBaoHoang/source/api/tests/test_api.py
            
            